# Generated by Django 3.0.7 on 2020-07-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
    ]
